---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./external-dns.yaml
  - ./cert-manager-webhook-ovh.yaml
  - ./hajimari.yaml
  - ./traefik.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./bjw-s-charts.yaml
